# image: alpine:latest
image: node:14.17-alpine

variables:
    BUILD_TYPE: release

ci_test:
    only:
        changes:
            - src/**/*
            - package.json
            - webpack.*
    cache:
        key: npm-cache
        paths: [ .npm ]
    before_script:
        - npm config set cache .npm
        - npm install
    script:
        - echo ${BUILD_TYPE}
        - npm run build:prod
